### ISSUE TITLE
"Via" information from exception is lost

### ISSUE THREAD

**Issue by xiongtx** [camdez/honeybadger#7]
## Expected behavior

The `:via` information in an exception is made available to Honeybadger.

Honeybadger [supports nested exceptions for Ruby](http://blog.honeybadger.io/honeybadger-now-supports-causes-nested-exceptions/). I'm not sure whether how this should be done via the [`notify` API](http://docs.honeybadger.io/guides/api.html#sample-payload).

## Actual behavior

`:via` information is lost.

## Steps to reproduce

The `:via` information is available after `normalize->event`:

```clojure
(let [e (Exception. "Exception with cause" (Exception. "Cause"))]
  (clojure.pprint/pprint
   (normalize->event "api-key" "env" e {})))

;; => 

{:metadata ...,
 :api-key "api-key",
 :env :env,
 :exception #error {:cause "Cause"
                    :via
                    [{:type java.lang.Exception
                      :message "Exception with cause"
                      :at ...}
                     {:type java.lang.Exception
                      :message "Cause"
                      :at ...}]
                    :trace ...}}
```

but elided by `event->notice`:

```clojure
{:notifier ... ,
 :server ... ,
 :error {:message "Exception with cause",
         :class "java.lang.Exception",
         :backtrace ... ,
         :tags #{}},
 :request ...}
```

**Comment by camdez** [comment]
Resolved in v0.4.0. Thanks!
